# Generated by Django 5.0.2 on 2024-03-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ident_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_exp_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.city')),
                ('id_ident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.identificationtype')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.user')),
            ],
        ),
    ]
